name: CI/CD Pipeline

on:
  push:
    branches: ['main'] #déclenché sur push
  pull_request:
    branches: ['main'] #déclenché sur PR

jobs:
  #Job1 : lint
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4 #clone le repo
      - uses: actions/setup-node@v4 #installe Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  #Job2 : Tests unitaires
  test-unit:
    name: Tests unitaires
    runs-on: ubuntu-latest
    need: lint # lance seulement si lint passe
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4 #clone le repo
      - uses: actions/setup-node@v4 #installe Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - name: installation des dépendances
        run: npm ci

      - name: Tests unitaires avec couverture
        run: npm run test -- --coverage

      - name: Upload rapport de couverture
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-prod
          path: coverage/
          retention-days: 30

  #Job3 : Tests intégration
  test-integration:
    name: Tests intégration
    runs-on: ubuntu-latest
    need: lint # lance seulement si lint passe
    steps:
      - uses: actions/checkout@v4 #clone le repo
      - uses: actions/setup-node@v4 #installe Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - name: installation des dépendances
        run: npm ci

      - name: Tests intégration
        run: npm run test
        env : 
          NODE_ENV: test

  #Job4 : Build 
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test-integration, test-unit] # lance seulement si test passe
    steps:
      - uses: actions/checkout@v4 #clone le repo
      - uses: actions/setup-node@v4 #installe Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - name: installation des dépendances
        run: npm ci
      - name: build de production
        run: npm run build --if-present

  #Job5 : Deploy
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build  # lance seulement si test passe
    if: github.event_name == 'push' #déclenché seulement sur push / pas sur les PR
    steps:
      # - name: Deployer vers render
      #   run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Verification du service
        run: curl --fail --silent --show-error -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}